apiVersion: apps/v1
kind: Deployment
metadata:
  name: ornek-uygulama
  labels:
    app: ornek-uygulama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ornek-uygulama
  template:
    metadata:
      labels:
        app: ornek-uygulama
    spec:
      containers:
      - name: ornek-uygulama
        image: mineergin/ornek-uygulama:latest # Docker Hub imaj adı ve tag
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret